version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ev_charging_system
      - MYSQL_USER=evuser
      - MYSQL_PASSWORD=evpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./central/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - evnet

volumes:
  mariadb_data:

networks:
  evnet: